version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: postgres
  superset:
    image: mnagaku/superset
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    container_name: superset
  jupyter:
    image: niicloudoperation/notebook
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jupyter
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/evaluation-tracer.git ; jupyter notebook --NotebookApp.token='etpassword'"
volumes:
  postgres:
    external: false
  redis:
    external: false
