---
- hosts: all
  connection: docker 
  user: root
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: execute superset-init
      command: superset-init --username admin --firstname admin --lastname user --email admin@et.jp --password etpassword
      tags:
        - init

    - name: find css file
      find:
          paths: /usr/local/lib/python3.5/dist-packages/superset/static/assets/dist
          patterns: 'theme.*.css'
      register: css_filename
      tags:
        - change_css

    - name: set css background jpg
      lineinfile:
          path: "{{css_filename.files[0].path}}"
          line: "body {\n  background-image: url(\"bg.jpg\");"
          regexp: 'body {'
      tags:
        - change_css

    - name: wget jpg
      get_url:
        url: https://img.animatetimes.com/news/visual/2017/1499070324_1_7_fe618586985b5ddc3b8da42e58b81d2e.jpg
        dest: /usr/local/lib/python3.5/dist-packages/superset/static/assets/dist/bg.jpg
      tags:
        - get_jpg
